common-obj-y += rng.o rng-egd.o
common-obj-$(CONFIG_POSIX) += rng-random.o

common-obj-$(CONFIG_TPM) += tpm.o

common-obj-y += hostmem.o hostmem-ram.o
common-obj-$(CONFIG_LINUX) += hostmem-file.o

common-obj-$(call lnot,$(CONFIG_XEN)) += cryptodev.o
common-obj-$(call lnot,$(CONFIG_XEN)) += cryptodev-builtin.o
